version: "3.9"
services:
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: MSVCS
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
  zipkin:
    image: openzipkin/zipkin
    container_name: "zipkin"
    ports:
      - '9411:9411'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    container_name: 'elasticsearch'
    ports:
        - "9200:9200"
        - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    links:
      - elasticsearch
