# To use from local files
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server.port: 8099
spring.application.name: msvc-config

management.endpoints.web.exposure.include: busrefresh


### For symmetric encryption
#encrypt.key: kjboihb34ouiytbkuhiuvyb347iutb3u4g

encrypt:
  key-store:
    location: classpath:/keystore/apiEncryptionKey.jks
    password: '1q2w3e4r'
    alias: apiEncryptionKey

### For having properties from git repo
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: my git repo to get properties
#          username: myname
#          password: mypass


#          clone-on-start: true
