# To use from local files
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server.port: 8099
spring.application.name: msvc-config

management.endpoints.web.exposure.include: busrefresh
#
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: my git repo to get properties
#          username: myname
#          password: mypass


#          clone-on-start: true
