### Check Configs msvc-users
GET http://localhost:8099/msvc-users/default

### Check Configs msvc-albums
GET http://localhost:8099/msvc-albums/default

### Trigger bus update
POST http://localhost:8099/actuator/busrefresh

### Check msvc-user was updated
GET http://localhost:8010/msvc-users/users/status

### Actuator
POST http://localhost:8099/actuator/health

### Encrypt
POST http://localhost:8099/encrypt

hello_world

### Decrypt
POST http://localhost:8099/decrypt

AQB+YtEYwpYfcrWhar/ma7f620Wv69ne+EWm+QlPEhTku4QRJGdd53r+CV1TJSAZL0jGQA4AULXWXQuQeeDkleXqL/UyFCk4Vle1iuDyAMQ6XEyqab8jWJ+XILOOx6wFZM1OL8j4VSn14kZDxSfTcGZBWsmVuMd6LhrkRhSeqVQ0HdVP8w+A+Ld8PTo58zVv2YBORfZLJYFlJkJ7ZbcjbuqEQ/2ht6G3DOEQoi4QIwxlAmnUgKAv1BtPsUJ4ozSEWV2WVzf1pnJeu9230a9Y7Kxb0P/WwAfebvipVKL+WawY0953NqjoWV2j3I+fqHk66bwCSr0ekZiDPB+zXU+Dz6cQztmA4gS6bxI0APrE7WIkGOquIYwqS0wbAxJkpVLQSdE=