### Actuator Health
GET http://localhost:8010/msvc-users/actuator/health

### Actuator Circuit breaker events
GET http://localhost:8010/msvc-users/actuator/circuitbreakerevents

### API Default
GET http://localhost:8010/msvc-users/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI3ZWIxMGJhNi01OWVlLTQ4MjQtYTE5OC1iNjE0NWVhY2I3ZWIiLCJleHAiOjE2NTAwNjE4ODB9.La0INoCth5hLad1pbHYtm8I52zvdm7vSxScy_SXDINunz1NZ6roG3mjgOQQlH2E3Azdoek1ttbM6EnCEkDaIHQ

### Create
POST http://localhost:8010/msvc-users/users
Content-Type: application/json

{
  "firstName": "James",
  "lastName": "Bond",
  "password": "agent007",
  "email": "JamesBond@email.com"
}

### Login
POST http://localhost:8010/msvc-users/login
Content-Type: application/json

{
  "login": "JamesBond@email.com",
  "password": "agent007"
}

### GetById
GET http://localhost:8010/msvc-users/users/708e3b74-97b2-4cb4-9e83-60916721287f
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI3MDhlM2I3NC05N2IyLTRjYjQtOWU4My02MDkxNjcyMTI4N2YiLCJleHAiOjE2NTExNjkxNjZ9.SRy_Z1xO94IIKhSOOsijwCikCppweXkCoN5a5LuZMMzDS7_S0OR3T_iU_4As8YOqrXm6cXA9nZIQG8Wf7_OnBQ