### API Default
GET http://localhost:8010/msvc-users/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI3ZWIxMGJhNi01OWVlLTQ4MjQtYTE5OC1iNjE0NWVhY2I3ZWIiLCJleHAiOjE2NTAwNjE4ODB9.La0INoCth5hLad1pbHYtm8I52zvdm7vSxScy_SXDINunz1NZ6roG3mjgOQQlH2E3Azdoek1ttbM6EnCEkDaIHQ

### Mapping
GET http://localhost:8010/users


### Create
POST http://localhost:8010/msvc-users/users
Content-Type: application/json

{
  "firstName": "James",
  "lastName": "Bond",
  "password": "agent007",
  "email": "JamesBond@email.com"
}

### Login
POST http://localhost:8010/msvc-users/login
Content-Type: application/json

{
  "login": "JamesBond@email.com",
  "password": "agent007"
}

### GetById
GET http://localhost:8010/msvc-users/users/9bdeed23-8ca6-4141-ae5e-6d4e58f40a58
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5YmRlZWQyMy04Y2E2LTQxNDEtYWU1ZS02ZDRlNThmNDBhNTgiLCJleHAiOjE2NTEwNzY1MzR9.qub2dd0RxxZTgYij3kG69TYrDHfIllYkp0pq16J3wNbcLGq0SaE255IsUW1o_tKtKO3srG3Qc97OfuxfnFTYjQ