gateway.host: localhost
eureka:
  client.service-url.defaultZone: http://localhost:8100/eureka
  instance.instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  devtools.restart.enabled: true
  sleuth.sampler.probability: '1.0'
  zipkin:
    base-url: 'http://localhost:9411'
    sender.type: web
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: 'jdbc:mysql://localhost:3306/MSVCS'
    username: root
    password:
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

token:
  expiration_time: 864000000
  secret: '{cipher}AQB7Oju4FPxnew2W1IZOLYB3m2nur7aDB0f8ZE/tLmjDs7dZ+h1ythYfO/CJb/u3ExL7Jza6bIYZEDoWsbjCpA8TFAu+sJ8W2JipooiQtLQTlk6tTgV+kusOu9RqslcG+rNsrCGOLzSV9qQ2BK6mnmk+GaktopFd4huTz/FOijwA1Qhf34lfQCR4J11KoekSghLFq4oTjHcpqQS4j2jqNS6p5rSxYZtpLPJPv3qRMNbRQnAzEwzQKZ5eWpAc/6pqotwd5vcNbfOs2iQJw8i/4J9qOb6ReLJYuVi4IQrULHrmAPsPs3FapOw7Q6CV4SL/8/qwoFaRoPRKLp5pPWXzkQnU0H3ZxLE1FPYg8Y0O93x0xr+zxPYs8uvjrIzjjVBX5JI='

msvc:
  albums.url: 'http://MSVC-ALBUMS/users/%s/albums'

management.endpoints.web.exposure.include: "*"

logging:
  file:
    name: ${spring.application.name}.log
